name: Docker
on:
  release:
    types:
      - published

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker build & tagging & push
        run: |
          REPOSITORY_URL=${{ secrets.DOCKERHUB_USERNAME }}/aws-cli-with-terraform
          docker build --tag $REPOSITORY_URL:latest .
          IMAGE_TAG=$(echo ${{ github.ref }} | sed '/^refs\/tags\//d')
          docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker push $REPOSITORY_URL:latest
          docker push $REPOSITORY_URL:$IMAGE_TAG
