name: Docker
on:
  release:
    types:
      - published

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build --tag aws-cli-with-terraform:latest .

      - name: tagging
        run: docker tag aws-cli-with-terraform:latest aws-cli-with-terraform:${{ github.ref }}

      - name: DockerHub login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}



